name: cleanup

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '31 20 * * *'    
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_UAT_CREDENTIALS }}
        #see https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux
        #    az account list-locations -o table

      - name: Set default Azure subscription
        run: az account set -s ${{ secrets.AZURE_UAT_SUBSCRIPTION_ID }}
      
      - name: Check the resource group exists
        id: rg_exists
        run: |
          RG_EXISTS=$(az group exists --name ${{ secrets.AZURE_UAT_RESOURCE_GROUP }} --subscription ${{ secrets.AZURE_UAT_SUBSCRIPTION_ID }})
          if [[ -z $RG_EXISTS ]]; then
            echo "RG does NOT exist"
            echo '::set-output name=RG_EXISTS::false'
          elif [[ $RG_EXISTS == "true" ]]; then
            echo "RG does exist"
            echo '::set-output name=RG_EXISTS::true'
          else
            echo "RG does NOT exist"
            echo '::set-output name=RG_EXISTS::false'
          fi

      - name: Remove deployed resource group (if exists)
        if: ${{ steps.rg_exists.outputs.RG_EXISTS }} == "true"
        run: |
          echo "${{ steps.rg_exists.outputs.RG_EXISTS }}"
          echo "${{ steps.rg_exists.RG_EXISTS }}"
          az group delete --resource-group ${{ secrets.AZURE_UAT_RESOURCE_GROUP }} --subscription ${{ secrets.AZURE_UAT_SUBSCRIPTION_ID }} --yes
      