name: infra-validation

on:
  workflow_dispatch:
  
  #pull_request:
  #  branches:
  #    - main
  #  paths:
  #    - 'scripts/**'
    
jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v2
        
      - name: Validate deployment template(s)
        run: |
          az bicep build --file ./deployment-rg.bicep
          az bicep build --file ./deployment-uat.bicep
